sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc
 - dmd
script:
 - dub run -- --compiler=$DC
 - make test-nobuild
 - dub clean
 - make clean
 - make test DCOMPILER=$DC
 - if [[ "$TRAVIS_OS_NAME" == "linux" && "$DC" == "dmd"]]; then make test-codecov; fi
