sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc
 - dmd
script:
 - dub run -- --compiler=$DC
 - make test-nobuild
 - dub clean
 - make clean
 - make test DCOMPILER=$DC
 - if [[ "$TRAVIS_OS_NAME" == "osx" && "$DC" == "dmd" ]]; then make test-codecov; fi
after_success:
 - if [[ "$TRAVIS_OS_NAME" == "osx" && "$DC" == "dmd" ]]; then bash <(curl -s https://codecov.io/bash); fi
 
