# Workflow to run a D compile on Windows. No tests, just the build step. 
name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build tsv-utils on Windows
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        dc: [dmd-latest, ldc-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Dub Build and Run
        shell: bash
        run: |
          dub run
          dub clean
          make clean

      - name: make unittest
        # Currently, only run unit tests on DMD. LDC has failures due to numeric formatting.
        if: ${{ startsWith(matrix.dc, 'dmd' }}
        shell: bash
        run: |
          make unittest DCOMPILER=${DC} DFLAGS=-m64
